### ISSUE TITLE
Can't make it work with nextjs

### ISSUE THREAD

**Issue by softmarshmallow** [udevbe/react-canvaskit#16]
Gets 
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/~/node_modules/react-canvaskit/dist/index.js
require() of ES modules is not supported.
require() of /Users/~/node_modules/react-canvaskit/dist/index.js from /Users/~/app/.next/server/pages/demo/react-canvaskit.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/~/node_modules/react-canvaskit/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1080:13)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at eval (webpack-internal:///react-canvaskit:1:18)
    at Object.react-canvaskit (/Users/~/app/.next/server/pages/demo/react-canvaskit.js:126:1)
    at __webpack_require__ (/Users/~/app/.next/server/pages/demo/react-canvaskit.js:23:31)
    at eval (webpack-internal:///./pages/demo/react-canvaskit.tsx:6:73)
    at Module../pages/demo/react-canvaskit.tsx (/Users/~/app/.next/server/pages/demo/react-canvaskit.js:104:1)
    at __webpack_require__ (/Users/~/app/.next/server/pages/demo/react-canvaskit.js:23:31)
    at /Users/~/app/.next/server/pages/demo/react-canvaskit.js:91:18
    at Object.<anonymous> (/Users/~/app/.next/server/pages/demo/react-canvaskit.js:94:10)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32) {
  code: 'ERR_REQUIRE_ESM'
}
```

Then i remove `"type": "module",` manually, i get this.

`SyntaxError: Unexpected token 'export'`

**Comment by Zubnix** [comment]
It seems you are using commonjs way of importing ie. `const bar = require('foo')`, which react-canvaskit isn't configured for. If you can, you can try switching to es modules way of importing modules `import bar from 'foo'` in your project.
